using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TravelPlanner.ReportService.Models.Reports;

namespace TravelPlanner.ReportService.Generation.Reports
{
    public class TravelPlanReportGenerator : ITravelPlanReportGenerator
    {
        public byte[] Generate(TravelPlanReportData reportData)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(35);

                    page.Header()
                        .Row(row =>
                        {
                            row.RelativeItem()
                                .Column(column =>
                                {
                                    column.Item().Text("Travel Plan Report").FontSize(24).Bold();
                                    column.Item().Text("Generated by TravelPlanner").FontSize(10).FontColor(Colors.Grey.Darken1);
                                });

                            row.ConstantItem(120)
                                .AlignRight()
                                .Text(DateTime.Now.ToString("dd.MM.yyyy HH:mm"))
                                .FontSize(10)
                                .FontColor(Colors.Grey.Darken1);
                        });

                    page.Content()
                        .PaddingVertical(15)
                        .Column(column =>
                        {
                            column.Spacing(14);

                            AddTripInfo(column, reportData);
                            AddDestinations(column, reportData);
                            AddActivities(column, reportData);
                            AddExpenses(column, reportData);
                            AddChecklist(column, reportData);
                            AddReminders(column, reportData);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("TravelPlanner • ");
                            text.CurrentPageNumber();
                            text.Span(" / ");
                            text.TotalPages();
                        });
                });
            }).GeneratePdf();
        }

        private static void AddTripInfo(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            var plan = reportData.TravelPlan;

            column.Item().Text(plan.Title).FontSize(18).Bold();
            column.Item().Text($"Period: {plan.StartDate:dd.MM.yyyy} - {plan.EndDate:dd.MM.yyyy}");
            column.Item().Text($"Budget: {plan.Budget:N2}");
            column.Item().Text($"Description: {plan.Description ?? "-"}");
            column.Item().Text($"Notes: {plan.Notes ?? "-"}");

            if (reportData.BudgetSummary != null)
            {
                column.Item().Text("Budget Summary").FontSize(14).Bold();
                column.Item().Text($"Planned budget: {reportData.BudgetSummary.PlannedBudget:N2}");
                column.Item().Text($"Total expenses: {reportData.BudgetSummary.TotalExpenses:N2}");
                column.Item().Text($"Remaining budget: {reportData.BudgetSummary.RemainingBudget:N2}");
                column.Item().Text($"Over budget: {(reportData.BudgetSummary.IsOverBudget ? "Yes" : "No")}");
            }
        }

        private static void AddDestinations(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            column.Item().Text("Destinations").FontSize(16).Bold();

            if (reportData.Destinations.Count == 0)
            {
                column.Item().Text("No destinations added.");
                return;
            }

            foreach (var destination in reportData.Destinations)
            {
                column.Item().Text($"{destination.Name} - {destination.Location}").Bold();
                column.Item().Text($"{destination.StartDate:dd.MM.yyyy} - {destination.EndDate:dd.MM.yyyy}");
                column.Item().Text(destination.Notes ?? "-");
            }
        }

        private static void AddActivities(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            column.Item().Text("Activities").FontSize(16).Bold();

            if (reportData.CalendarDays.Count == 0)
            {
                column.Item().Text("No activities added.");
                return;
            }

            foreach (var day in reportData.CalendarDays)
            {
                column.Item().Text($"{day.Date:dd.MM.yyyy}").Bold();

                foreach (var activity in day.Activities)
                {
                    column.Item().Text($"{activity.StartTime} - {activity.EndTime} | {activity.Title} | {activity.Location}");
                }
            }
        }

        private static void AddExpenses(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            column.Item().Text("Expenses").FontSize(16).Bold();

            if (reportData.Expenses.Count == 0)
            {
                column.Item().Text("No expenses added.");
                return;
            }

            foreach (var expense in reportData.Expenses)
            {
                column.Item().Text($"{expense.ExpenseDate:dd.MM.yyyy} | {expense.Title} | {expense.Category} | {expense.Amount:N2}");
            }
        }

        private static void AddChecklist(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            column.Item().Text("Checklist").FontSize(16).Bold();

            if (reportData.ChecklistItems.Count == 0)
            {
                column.Item().Text("No checklist items added.");
                return;
            }

            foreach (var item in reportData.ChecklistItems)
            {
                column.Item().Text($"{(item.IsCompleted ? "✓" : "□")} {item.Title}");
            }
        }

        private static void AddReminders(ColumnDescriptor column, TravelPlanReportData reportData)
        {
            column.Item().Text("Reminders").FontSize(16).Bold();

            if (reportData.Reminders.Count == 0)
            {
                column.Item().Text("No reminders added.");
                return;
            }

            foreach (var reminder in reportData.Reminders.OrderBy(reminder => reminder.ReminderAt))
            {
                column.Item()
                    .BorderBottom(1)
                    .BorderColor(Colors.Grey.Lighten2)
                    .PaddingBottom(5)
                    .Column(item =>
                    {
                        item.Spacing(2);

                        item.Item().Text($"{reminder.Title}").Bold();

                        item.Item().Text(
                            $"Time: {reminder.ReminderAt:dd.MM.yyyy HH:mm} | Status: {reminder.Status}"
                        );

                        if (!string.IsNullOrWhiteSpace(reminder.Description))
                        {
                            item.Item().Text($"Description: {reminder.Description}");
                        }

                        if (reminder.CompletedAt.HasValue)
                        {
                            item.Item().Text($"Completed at: {reminder.CompletedAt.Value:dd.MM.yyyy HH:mm}");
                        }
                    });
            }
        }

    }
}