using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace TravelPlanner.ReportService.Generation.Reports
{
    public class TravelPlanReportGenerator : ITravelPlanReportGenerator
    {
        public byte[] Generate()
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("Travel Plan Report")
                        .FontSize(24)
                        .Bold();

                    page.Content()
                        .PaddingVertical(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item().Text("Report generation is connected successfully.");
                            column.Item().Text("Real travel plan data will be added in the next step.");
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by TravelPlanner");
                        });
                });
            }).GeneratePdf();
        }
    }
}